name: team-09-sperrins

on:
  push:
    branches:
  pull_request:



jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    # implement make file execution
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      #Set up python
      - name: use-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Run all checks
        run: make all